package bbms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brian
 */
public class GUI_NB extends javax.swing.JFrame {
    
    GUIMainDisp GMD = new GUIMainDisp();

    /**
     * Creates new form BBGUI
     */
    public GUI_NB() {
        initComponents();
        setJMenuBar(new GUIMenu());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayPanel = new javax.swing.JPanel();
        DisplayTabs = new javax.swing.JTabbedPane();
        MainDisplay = new GUIMainDisp();
        InformationPanel = new javax.swing.JPanel();
        BasicInfoPane = new GUIBasicInfo();
        BI_Hex = new javax.swing.JLabel();
        BI_HexType = new javax.swing.JLabel();
        BI_HexElev = new javax.swing.JLabel();
        BI_HexObsc = new javax.swing.JLabel();
        BI_HexDens = new javax.swing.JLabel();
        BI_HexOHeight = new javax.swing.JLabel();
        BI_UpperDisp = new javax.swing.JLabel();
        BI_LowerDisp = new javax.swing.JLabel();
        DetailedInfoPane = new javax.swing.JPanel();
        MiniMap = new javax.swing.JPanel();
        ConsolePanel = new javax.swing.JPanel();
        ConsoleScroll = new javax.swing.JScrollPane();
        GUIConsole = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bare Bones Military Simulator");
        setMaximumSize(new java.awt.Dimension(1024, 800));
        setMinimumSize(new java.awt.Dimension(1024, 800));
        setPreferredSize(new java.awt.Dimension(1024, 800));
        setResizable(false);

        DisplayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        DisplayTabs.setPreferredSize(new java.awt.Dimension(710, 530));

        MainDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainDisplayMouseClicked(evt);
            }
        });
        MainDisplay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MainDisplayMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout MainDisplayLayout = new javax.swing.GroupLayout(MainDisplay);
        MainDisplay.setLayout(MainDisplayLayout);
        MainDisplayLayout.setHorizontalGroup(
            MainDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        MainDisplayLayout.setVerticalGroup(
            MainDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        DisplayTabs.addTab("Main Display", MainDisplay);

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        InformationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));

        BasicInfoPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Info"));

        BI_Hex.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BI_Hex.setText("Hex: (xxx, yyy)");

        BI_HexType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BI_HexType.setText("Hex Type");

        BI_HexElev.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BI_HexElev.setText("Elev: xxxm");

        BI_HexObsc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BI_HexObsc.setText("Obsc: xxx");

        BI_HexDens.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BI_HexDens.setText("Density: xxx");

        BI_HexOHeight.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BI_HexOHeight.setText("Obs H: xxm");

        BI_UpperDisp.setText("Upper Hex Display");

        BI_LowerDisp.setText("Lower Hex Display");

        javax.swing.GroupLayout BasicInfoPaneLayout = new javax.swing.GroupLayout(BasicInfoPane);
        BasicInfoPane.setLayout(BasicInfoPaneLayout);
        BasicInfoPaneLayout.setHorizontalGroup(
            BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicInfoPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BI_LowerDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BI_UpperDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BasicInfoPaneLayout.createSequentialGroup()
                        .addGroup(BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BI_Hex)
                            .addComponent(BI_HexObsc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BI_HexType)
                            .addComponent(BI_HexDens))
                        .addGap(18, 18, 18)
                        .addGroup(BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BI_HexElev)
                            .addComponent(BI_HexOHeight)))))
        );
        BasicInfoPaneLayout.setVerticalGroup(
            BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicInfoPaneLayout.createSequentialGroup()
                .addGroup(BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BI_Hex)
                    .addComponent(BI_HexType)
                    .addComponent(BI_HexElev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BI_HexObsc)
                    .addComponent(BI_HexDens)
                    .addComponent(BI_HexOHeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BI_UpperDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BI_LowerDisp)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        DetailedInfoPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Unit Info"));

        javax.swing.GroupLayout DetailedInfoPaneLayout = new javax.swing.GroupLayout(DetailedInfoPane);
        DetailedInfoPane.setLayout(DetailedInfoPaneLayout);
        DetailedInfoPaneLayout.setHorizontalGroup(
            DetailedInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DetailedInfoPaneLayout.setVerticalGroup(
            DetailedInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        MiniMap.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout MiniMapLayout = new javax.swing.GroupLayout(MiniMap);
        MiniMap.setLayout(MiniMapLayout);
        MiniMapLayout.setHorizontalGroup(
            MiniMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MiniMapLayout.setVerticalGroup(
            MiniMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout InformationPanelLayout = new javax.swing.GroupLayout(InformationPanel);
        InformationPanel.setLayout(InformationPanelLayout);
        InformationPanelLayout.setHorizontalGroup(
            InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MiniMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(BasicInfoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DetailedInfoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InformationPanelLayout.setVerticalGroup(
            InformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationPanelLayout.createSequentialGroup()
                .addComponent(BasicInfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DetailedInfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MiniMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConsolePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 3));

        GUIConsole.setEditable(false);
        GUIConsole.setColumns(20);
        GUIConsole.setRows(5);
        ConsoleScroll.setViewportView(GUIConsole);

        javax.swing.GroupLayout ConsolePanelLayout = new javax.swing.GroupLayout(ConsolePanel);
        ConsolePanel.setLayout(ConsolePanelLayout);
        ConsolePanelLayout.setHorizontalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsoleScroll)
        );
        ConsolePanelLayout.setVerticalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsoleScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainDisplayMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainDisplayMouseMoved
        GUIMainDisp.MouseMotionEvents(evt);
    }//GEN-LAST:event_MainDisplayMouseMoved

    private void MainDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainDisplayMouseClicked
        GMD.MouseClickedEvents(evt);
    }//GEN-LAST:event_MainDisplayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        
        }
        catch (Exception e) {
            System.err.println("ERROR: Cannot load Windows-like displays.");
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GlobalFuncs.gui = new GUI_NB();
                GlobalFuncs.gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BI_Hex;
    public javax.swing.JLabel BI_HexDens;
    public javax.swing.JLabel BI_HexElev;
    public javax.swing.JLabel BI_HexOHeight;
    public javax.swing.JLabel BI_HexObsc;
    public javax.swing.JLabel BI_HexType;
    public javax.swing.JLabel BI_LowerDisp;
    public javax.swing.JLabel BI_UpperDisp;
    public javax.swing.JPanel BasicInfoPane;
    private javax.swing.JPanel ConsolePanel;
    private javax.swing.JScrollPane ConsoleScroll;
    private javax.swing.JPanel DetailedInfoPane;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JTabbedPane DisplayTabs;
    private static javax.swing.JTextArea GUIConsole;
    private javax.swing.JPanel InformationPanel;
    private javax.swing.JPanel MainDisplay;
    private javax.swing.JPanel MiniMap;
    // End of variables declaration//GEN-END:variables

    /**
     * Prints output to the GUI Console output.  Automatically appends newline.
     */
    public static void GCO(String str) {
    	GUIConsole.append(str + "\n");
    	GUIConsole.setCaretPosition(GUIConsole.getDocument().getLength());		
    }
    
}
